import SideBar from "@/components/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <div className="flex w-full h-screen bg-gray-100">
      <SideBar />
      <main className="overflow-auto w-full">{children}</main>
    </div>
  );
}
